/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courier;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author jasmi
 */
public class ViewOrderDetails extends javax.swing.JFrame {

    /**
     * Creates new form ViewOrderDetails
     */
    String Userid = "";
    public ViewOrderDetails(String UserID) {
        initComponents();
        Userid = UserID;
        deliverystatuscbox.setEditable(false);
        deletebtn.setVisible(false);
        
        try{
            File file = new File("UserDetails.txt");
            File file1 = new File("Orders.txt");
            Scanner sc = new Scanner(file); 
            Scanner sc1 = new Scanner(file1); 
            //read data from the file

            String temp;
            String temp1;
            boolean found = false;

            while(sc.hasNext() && !found /*the system will stop running while it found the correct username and password*/) {
                temp = sc.nextLine(); //read a line of text from file
                String[] tempArr;
                tempArr = temp.split (","); 
                        
                        if (Userid.equals(tempArr[0])) {
                           String Temptype = tempArr[2];

                            if(Temptype.equals("Customer")){
                                deletebtn.setVisible(true);
                            }
                                while(sc1.hasNext() && !found) {
                                    temp1 = sc1.nextLine();
                                    String [] temp1Arr;
                                    temp1Arr = temp1.split(",");
                                        namesenderlbl.setText(temp1Arr[1]);
                                        addressSenderlbl.setText(temp1Arr[2]);
                                        phonesenderlbl.setText(temp1Arr[3]);
                                        emailsenderlbl.setText(temp1Arr[4]);
                                        namereceiverlbl.setText(temp1Arr[5]);
                                        addressReceiverlbl.setText(temp1Arr[6]);
                                       phonereceiverlbl.setText(temp1Arr[7]);
                                        emailreceiverlbl.setText(temp1Arr[8]);
                                        orderidlbl.setText(temp1Arr[0]);
                                        custidlbl.setText(temp1Arr[21]);
                                        deliveryidlbl.setText(temp1Arr[19]);
                                        datelbl.setText(temp1Arr[9]);
                                        weight1lbl.setText(temp1Arr[10]);
                                        width1lbl.setText(temp1Arr[11]);
                                        length1lbl.setText(temp1Arr[12]);
                                        height1lbl.setText(temp1Arr[13]);
                                        detailsOrderlbl.setText(temp1Arr[14]);
                                        shippingfee1lbl.setText(temp1Arr[15]);
                                        itemprice1lbl.setText(temp1Arr[16]);
                                        total1lbl.setText(temp1Arr[17]);
                                        phonestafflbl.setText(temp1Arr[20]);
                                        deliverystatuscbox.setSelectedItem(temp1Arr[18]);
                                }
                        }
            }
        }catch(FileNotFoundException ex) {
            ex.toString();
        }
                                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliverystatuscbox = new javax.swing.JComboBox<>();
        backbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        kglbl = new javax.swing.JLabel();
        deliverysenderlbl = new javax.swing.JLabel();
        deliverystatuslbl = new javax.swing.JLabel();
        assignedpersonphonelbl1 = new javax.swing.JLabel();
        deliveryreceiverlbl = new javax.swing.JLabel();
        orderdetailslbl = new javax.swing.JLabel();
        shippingfeelbl = new javax.swing.JLabel();
        itempricelbl = new javax.swing.JLabel();
        totallbl = new javax.swing.JLabel();
        Datelbl = new javax.swing.JLabel();
        weightlbl = new javax.swing.JLabel();
        deliveryOrderlbl = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        itemlbl = new javax.swing.JLabel();
        itemlbl1 = new javax.swing.JLabel();
        lengthlbl = new javax.swing.JLabel();
        idorderlbl = new javax.swing.JLabel();
        widthlbl = new javax.swing.JLabel();
        orderidlbl = new javax.swing.JLabel();
        heightlbl = new javax.swing.JLabel();
        idcustlbl = new javax.swing.JLabel();
        Wcmlbl = new javax.swing.JLabel();
        custidlbl = new javax.swing.JLabel();
        Lcmlbl = new javax.swing.JLabel();
        iddeliverylbl = new javax.swing.JLabel();
        Hcmlbl = new javax.swing.JLabel();
        deliveryidlbl = new javax.swing.JLabel();
        receivernamelbl = new javax.swing.JLabel();
        receiveraddresslbl = new javax.swing.JLabel();
        receiverphonelbl = new javax.swing.JLabel();
        receiveremaillbl = new javax.swing.JLabel();
        sendernamelbl = new javax.swing.JLabel();
        senderaddresslbl = new javax.swing.JLabel();
        senderphonelbl = new javax.swing.JLabel();
        senderemaillbl = new javax.swing.JLabel();
        phonesenderlbl = new javax.swing.JLabel();
        addressReceiverlbl = new javax.swing.JLabel();
        namesenderlbl = new javax.swing.JLabel();
        emailsenderlbl = new javax.swing.JLabel();
        namereceiverlbl = new javax.swing.JLabel();
        phonereceiverlbl = new javax.swing.JLabel();
        emailreceiverlbl = new javax.swing.JLabel();
        emailreceiverlbl1 = new javax.swing.JLabel();
        width1lbl = new javax.swing.JLabel();
        weight1lbl = new javax.swing.JLabel();
        height1lbl = new javax.swing.JLabel();
        length1lbl = new javax.swing.JLabel();
        shippingfee1lbl = new javax.swing.JLabel();
        total1lbl = new javax.swing.JLabel();
        shippingfee1lbl2 = new javax.swing.JLabel();
        itemprice1lbl = new javax.swing.JLabel();
        phonestafflbl = new javax.swing.JLabel();
        addressSenderlbl = new javax.swing.JLabel();
        detailsOrderlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deliverystatuscbox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        deliverystatuscbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Processing", "Shipping", "Cancelled", "Delivered" }));

        backbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        kglbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        kglbl.setText("KG");

        deliverysenderlbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        deliverysenderlbl.setText("Sender Details");

        deliverystatuslbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        deliverystatuslbl.setText("Delivery Status:");

        assignedpersonphonelbl1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        assignedpersonphonelbl1.setText("Delivery Staff Contact No.: ");

        deliveryreceiverlbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        deliveryreceiverlbl.setText("Receiver Details");

        orderdetailslbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        orderdetailslbl.setText("Order Details: ");

        shippingfeelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        shippingfeelbl.setText("Shipping Fee:");

        itempricelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        itempricelbl.setText("Item Price:");

        totallbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        totallbl.setText("Total: ");

        Datelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Datelbl.setText("Date:");

        weightlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        weightlbl.setText("Weight:");

        deliveryOrderlbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        deliveryOrderlbl.setText("Delivery");

        datelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        itemlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        itemlbl.setText("RM");

        itemlbl1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        itemlbl1.setText("RM");

        lengthlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lengthlbl.setText("L:");

        idorderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        idorderlbl.setText("Orderid:");

        widthlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        widthlbl.setText("W:");

        heightlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        heightlbl.setText("H:");

        idcustlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        idcustlbl.setText("Custid:");

        Wcmlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Wcmlbl.setText("cm");

        Lcmlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Lcmlbl.setText("cm");

        iddeliverylbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        iddeliverylbl.setText("Deliveryid:");

        Hcmlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Hcmlbl.setText("cm");

        receivernamelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        receivernamelbl.setText("Receiver Name:");

        receiveraddresslbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        receiveraddresslbl.setText("Address:");

        receiverphonelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        receiverphonelbl.setText("Phone Number:");

        receiveremaillbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        receiveremaillbl.setText("Email Address:");

        sendernamelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        sendernamelbl.setText("Sender Name:");

        senderaddresslbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        senderaddresslbl.setText("Address:");

        senderphonelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        senderphonelbl.setText("Phone Number:");

        senderemaillbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        senderemaillbl.setText("Email Address:");

        phonesenderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        addressReceiverlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        namesenderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        emailsenderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        namereceiverlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        phonereceiverlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        emailreceiverlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        emailreceiverlbl1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        width1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        weight1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        height1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        length1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        shippingfee1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        total1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        shippingfee1lbl2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        itemprice1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        phonestafflbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        addressSenderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        detailsOrderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(sendernamelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namesenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deliverysenderlbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(senderphonelbl)
                                            .addComponent(senderemaillbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phonesenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailsenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(senderaddresslbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addressSenderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(deliveryreceiverlbl)
                                .addGap(147, 147, 147))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(receivernamelbl)
                                            .addComponent(receiverphonelbl)
                                            .addComponent(receiveraddresslbl)
                                            .addComponent(receiveremaillbl)))
                                    .addComponent(deliverystatuslbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deliverystatuscbox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namereceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phonereceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailreceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressReceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)))
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Datelbl)
                                    .addComponent(weightlbl)
                                    .addComponent(idorderlbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(datelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(orderidlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(457, 457, 457))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(deliveryOrderlbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(shippingfeelbl)
                                                    .addComponent(itempricelbl)
                                                    .addComponent(totallbl))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(itemlbl)
                                                            .addComponent(itemlbl1))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(total1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(itemprice1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(shippingfee1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(assignedpersonphonelbl1)
                                                .addGap(2, 2, 2)
                                                .addComponent(phonestafflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(orderdetailslbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(detailsOrderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(27, 27, 27)
                                                        .addComponent(length1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(height1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(idcustlbl)
                                                            .addComponent(custidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(75, 75, 75)
                                                        .addComponent(iddeliverylbl)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(deliveryidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Hcmlbl)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(weight1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kglbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(widthlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(width1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Wcmlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lengthlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113)
                                        .addComponent(Lcmlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(heightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                        .addComponent(deletebtn)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(564, Short.MAX_VALUE)
                    .addComponent(emailreceiverlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(160, 160, 160)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(196, 196, 196)
                    .addComponent(shippingfee1lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(546, 546, 546)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deliveryreceiverlbl)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(receivernamelbl)
                                    .addComponent(namereceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(receiveraddresslbl)
                                        .addGap(86, 86, 86))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(addressReceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(receiverphonelbl)
                                    .addComponent(phonereceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(receiveremaillbl)
                                    .addComponent(emailreceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deliverystatuscbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deliverystatuslbl)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deliverysenderlbl)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sendernamelbl)
                                    .addComponent(namesenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(senderaddresslbl)
                                        .addGap(86, 86, 86)
                                        .addComponent(senderphonelbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addressSenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phonesenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(senderemaillbl)
                                    .addComponent(emailsenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(deliveryOrderlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orderidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idorderlbl)
                    .addComponent(custidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idcustlbl)
                    .addComponent(deliveryidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddeliverylbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Datelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(weightlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kglbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(weight1lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(widthlbl)
                                        .addComponent(lengthlbl)
                                        .addComponent(Wcmlbl))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(heightlbl)
                                        .addComponent(Lcmlbl))
                                    .addComponent(width1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hcmlbl)
                                    .addComponent(height1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(shippingfeelbl)
                                            .addComponent(shippingfee1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(itempricelbl)
                                                .addComponent(itemlbl))
                                            .addComponent(itemprice1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(totallbl)
                                            .addComponent(itemlbl1)
                                            .addComponent(total1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(assignedpersonphonelbl1)
                                            .addComponent(phonestafflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(orderdetailslbl)
                                    .addComponent(detailsOrderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(length1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addComponent(deletebtn))
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(220, 220, 220)
                    .addComponent(emailreceiverlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(368, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(426, Short.MAX_VALUE)
                    .addComponent(shippingfee1lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(162, 162, 162)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Orders o= new Orders();
        o.Back(Userid);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String TempUserID = Userid;
        String ExistOrderID = orderidlbl.getText();
        String Tempcustid = custidlbl.getText();
        String deliveryid = deliveryidlbl.getText();
        String Tempsendname = namesenderlbl.getText();
        String Tempsendaddress = addressSenderlbl.getText();
        String Tempsendphone = phonesenderlbl.getText();
        String Tempsendemail = emailsenderlbl.getText();
        String Tempreceivename = namereceiverlbl.getText();
        String Tempreceiveaddress = addressReceiverlbl.getText();
        String Tempreceivephone= phonereceiverlbl.getText();
        String Tempreceiveemail = emailreceiverlbl.getText();
        String Tempdate = datelbl.getText();
        String Tempweight= weight1lbl.getText();
        String Tempwidth = width1lbl.getText();
        String Templength = length1lbl.getText();
        String Tempheight = height1lbl.getText();
        String Temporderdetails = detailsOrderlbl.getText();
        String Tempshippingfee= shippingfee1lbl.getText();
        String Tempitemprice = itemprice1lbl.getText();
        String Temptotal =total1lbl.getText();
        String Tempstaffphone = phonestafflbl.getText();
        String Tempdeliverystatus = deliverystatuscbox.getSelectedItem().toString();

        try{
            File file = new File("UserDetails.txt");
            Scanner sc = new Scanner(file);
            //read data from the file
            String temp;
            boolean found = false;

            while(sc.hasNext() && !found /*the system will stop running while it found the correct username and password*/) {
                temp = sc.nextLine(); //read a line of text from file
                String[] tempArr;
                tempArr = temp.split (",");
                if (TempUserID.equals(tempArr[0])) {
                    String Temptype = tempArr[2];
                    Users u = new Users();
                    u.setSelectedUserType(Temptype);

                    Orders o = new Orders(ExistOrderID, Tempsendname,Tempsendaddress,Tempsendphone,Tempsendemail,Tempreceivename,Tempreceiveaddress,Tempreceivephone,Tempreceiveemail,Tempdate,Tempweight,Tempwidth,
                        Templength,Tempheight,Temporderdetails,Tempshippingfee,Tempitemprice,Temptotal,Tempstaffphone,deliveryid,Tempdeliverystatus,Tempcustid);

                    if(u.getSelectedUserType().equals("Customer")) {
                       o.DeleteOrder();
                       this.dispose();
                       new DeliveryStaffOrderPage(Userid).setVisible(true);
                    }                            
                }
            }
        } catch(FileNotFoundException ex) {
            ex.toString();
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ViewOrderDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Datelbl;
    private javax.swing.JLabel Hcmlbl;
    private javax.swing.JLabel Lcmlbl;
    private javax.swing.JLabel Wcmlbl;
    private javax.swing.JLabel addressReceiverlbl;
    private javax.swing.JLabel addressSenderlbl;
    private javax.swing.JLabel assignedpersonphonelbl1;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel custidlbl;
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel deliveryOrderlbl;
    private javax.swing.JLabel deliveryidlbl;
    private javax.swing.JLabel deliveryreceiverlbl;
    private javax.swing.JLabel deliverysenderlbl;
    private javax.swing.JComboBox<String> deliverystatuscbox;
    private javax.swing.JLabel deliverystatuslbl;
    private javax.swing.JLabel detailsOrderlbl;
    private javax.swing.JLabel emailreceiverlbl;
    private javax.swing.JLabel emailreceiverlbl1;
    private javax.swing.JLabel emailsenderlbl;
    private javax.swing.JLabel height1lbl;
    private javax.swing.JLabel heightlbl;
    private javax.swing.JLabel idcustlbl;
    private javax.swing.JLabel iddeliverylbl;
    private javax.swing.JLabel idorderlbl;
    private javax.swing.JLabel itemlbl;
    private javax.swing.JLabel itemlbl1;
    private javax.swing.JLabel itemprice1lbl;
    private javax.swing.JLabel itempricelbl;
    private javax.swing.JLabel kglbl;
    private javax.swing.JLabel length1lbl;
    private javax.swing.JLabel lengthlbl;
    private javax.swing.JLabel namereceiverlbl;
    private javax.swing.JLabel namesenderlbl;
    private javax.swing.JLabel orderdetailslbl;
    private javax.swing.JLabel orderidlbl;
    private javax.swing.JLabel phonereceiverlbl;
    private javax.swing.JLabel phonesenderlbl;
    private javax.swing.JLabel phonestafflbl;
    private javax.swing.JLabel receiveraddresslbl;
    private javax.swing.JLabel receiveremaillbl;
    private javax.swing.JLabel receivernamelbl;
    private javax.swing.JLabel receiverphonelbl;
    private javax.swing.JLabel senderaddresslbl;
    private javax.swing.JLabel senderemaillbl;
    private javax.swing.JLabel sendernamelbl;
    private javax.swing.JLabel senderphonelbl;
    private javax.swing.JLabel shippingfee1lbl;
    private javax.swing.JLabel shippingfee1lbl2;
    private javax.swing.JLabel shippingfeelbl;
    private javax.swing.JLabel total1lbl;
    private javax.swing.JLabel totallbl;
    private javax.swing.JLabel weight1lbl;
    private javax.swing.JLabel weightlbl;
    private javax.swing.JLabel width1lbl;
    private javax.swing.JLabel widthlbl;
    // End of variables declaration//GEN-END:variables
}
