/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courier;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author jasmi
 */
public class ViewOrderDetails extends javax.swing.JFrame {

    String Userid = "";
    String OrderID = "";
    
    public ViewOrderDetails(String UserID, String orderid) {
        initComponents();
        Userid = UserID;
        OrderID = orderid;
         setResizable(false);
        this.setLocationRelativeTo(null);
        setTitle("Fast & Furious Express");
        fillstatuscombo();
        deliverystatuscbox.setEditable(false);
        idorderlbl.setVisible(false);
        orderidlbl.setVisible(false);
        idcustlbl.setVisible(false);
        custidlbl.setVisible(false);
        iddeliverylbl.setVisible(false);
        deliveryidlbl.setVisible(false);
        deletebtn.setVisible(false);
        
        try{
            File file = new File("UserDetails.txt");
            File file1 = new File("Orders.txt");
            Scanner sc = new Scanner(file); 
            Scanner sc1 = new Scanner(file1); 
            //read data from the file

            String temp;
            String temp1;
            boolean found = false;

            while(sc.hasNext() && !found /*the system will stop running while it found the correct userid*/) {
                temp = sc.nextLine(); //read a line of text from file
                String[] tempArr;
                tempArr = temp.split (","); 
                        
                if (Userid.equals(tempArr[0])) {
                    String Temptype = tempArr[2];
                    deletebtn.setVisible(true);
                    Users u = new Users();
                    u.setSelectedUserType(Temptype);
                    
                    while(sc1.hasNext() && !found) {
                        temp1 = sc1.nextLine();
                        String [] temp1Arr;
                        temp1Arr = temp1.split(",");
                        
                        if(temp1Arr[0].equals(OrderID)) {
                            namesenderlbl.setText(temp1Arr[1]);
                            addressSenderlbl.setText(temp1Arr[2]);
                            phonesenderlbl.setText(temp1Arr[3]);
                            emailsenderlbl.setText(temp1Arr[4]);
                            namereceiverlbl.setText(temp1Arr[5]);
                            addressReceiverlbl.setText(temp1Arr[6]);
                            phonereceiverlbl.setText(temp1Arr[7]);
                            emailreceiverlbl.setText(temp1Arr[8]);
                            orderidlbl.setText(temp1Arr[0]);
                            custidlbl.setText(temp1Arr[21]);
                            deliveryidlbl.setText(temp1Arr[19]);
                            datelbl.setText(temp1Arr[9]);
                            weight1lbl.setText(temp1Arr[10]);
                            width1lbl.setText(temp1Arr[11]);
                            length1lbl.setText(temp1Arr[12]);
                            height1lbl.setText(temp1Arr[13]);
                            detailsOrderlbl.setText(temp1Arr[14]);
                            shippingfee1lbl.setText(temp1Arr[15]);
                            itemprice1lbl.setText(temp1Arr[16]);
                            total1lbl.setText(temp1Arr[17]);
                            deliverystatuscbox.setSelectedItem(temp1Arr[18]);
                            assignedperson1lbl.setText(temp1Arr[19]);
                            phonestafflbl.setText(temp1Arr[20]);
                         
                        if(Temptype.equals("Customer")) {
                            deliverystatuscbox.setEnabled(false);
                        }else if(Temptype.equals("Delivery Staff")) {
                            deletebtn.setText("Update");
                        }else{
                            deletebtn.setVisible(false);
                            deliverystatuscbox.setEnabled(false);
                            assignedperson1lbl.setEnabled(false);
                        }
                        }
                    }
                }
            }
        }catch(FileNotFoundException ex) {
            ex.toString();
        }
                                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        phonesenderlbl = new javax.swing.JLabel();
        senderphonelbl = new javax.swing.JLabel();
        senderaddresslbl = new javax.swing.JLabel();
        addressSenderlbl = new javax.swing.JLabel();
        deliverysenderlbl = new javax.swing.JLabel();
        sendernamelbl = new javax.swing.JLabel();
        senderemaillbl = new javax.swing.JLabel();
        emailsenderlbl = new javax.swing.JLabel();
        namesenderlbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        backbtn = new javax.swing.JButton();
        deliverystatuscbox = new javax.swing.JComboBox<>();
        phonereceiverlbl = new javax.swing.JLabel();
        emailreceiverlbl = new javax.swing.JLabel();
        deliverystatuslbl = new javax.swing.JLabel();
        deliveryreceiverlbl = new javax.swing.JLabel();
        receivernamelbl = new javax.swing.JLabel();
        receiveraddresslbl = new javax.swing.JLabel();
        receiverphonelbl = new javax.swing.JLabel();
        receiveremaillbl = new javax.swing.JLabel();
        addressReceiverlbl = new javax.swing.JLabel();
        namereceiverlbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        idcustlbl = new javax.swing.JLabel();
        itemlbl = new javax.swing.JLabel();
        Wcmlbl = new javax.swing.JLabel();
        Hcmlbl = new javax.swing.JLabel();
        Lcmlbl = new javax.swing.JLabel();
        detailsOrderlbl = new javax.swing.JLabel();
        idorderlbl = new javax.swing.JLabel();
        custidlbl = new javax.swing.JLabel();
        weightlbl = new javax.swing.JLabel();
        itemlbl2 = new javax.swing.JLabel();
        total1lbl = new javax.swing.JLabel();
        itempricelbl = new javax.swing.JLabel();
        heightlbl = new javax.swing.JLabel();
        width1lbl = new javax.swing.JLabel();
        deliveryOrderlbl = new javax.swing.JLabel();
        deliveryidlbl = new javax.swing.JLabel();
        itemlbl1 = new javax.swing.JLabel();
        assignedpersonlbl = new javax.swing.JLabel();
        shippingfeelbl = new javax.swing.JLabel();
        itemprice1lbl = new javax.swing.JLabel();
        totallbl = new javax.swing.JLabel();
        height1lbl = new javax.swing.JLabel();
        orderdetailslbl = new javax.swing.JLabel();
        orderidlbl = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();
        lengthlbl = new javax.swing.JLabel();
        assignedperson1lbl = new javax.swing.JLabel();
        length1lbl = new javax.swing.JLabel();
        weight1lbl = new javax.swing.JLabel();
        assignedpersonphonelbl1 = new javax.swing.JLabel();
        shippingfee1lbl2 = new javax.swing.JLabel();
        phonestafflbl = new javax.swing.JLabel();
        Datelbl = new javax.swing.JLabel();
        shippingfee1lbl = new javax.swing.JLabel();
        iddeliverylbl = new javax.swing.JLabel();
        widthlbl = new javax.swing.JLabel();
        kglbl = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(129, 182, 157));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        phonesenderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        senderphonelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        senderphonelbl.setText("Phone Number:");

        senderaddresslbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        senderaddresslbl.setText("Address:");

        addressSenderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        deliverysenderlbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        deliverysenderlbl.setText("Sender Details");

        sendernamelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        sendernamelbl.setText("Sender Name:");

        senderemaillbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        senderemaillbl.setText("Email Address:");

        emailsenderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        namesenderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(sendernamelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namesenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(senderphonelbl)
                                            .addComponent(senderemaillbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phonesenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailsenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(senderaddresslbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addressSenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(deliverysenderlbl)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(deliverysenderlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendernamelbl)
                    .addComponent(namesenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(senderaddresslbl)
                        .addGap(86, 86, 86)
                        .addComponent(senderphonelbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addressSenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phonesenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(senderemaillbl)
                    .addComponent(emailsenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 280));

        jPanel2.setBackground(new java.awt.Color(129, 182, 157));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        backbtn.setBackground(new java.awt.Color(129, 182, 157));
        backbtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        deliverystatuscbox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        deliverystatuscbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverystatuscboxActionPerformed(evt);
            }
        });

        phonereceiverlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        emailreceiverlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        deliverystatuslbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        deliverystatuslbl.setText("Delivery Status:");

        deliveryreceiverlbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        deliveryreceiverlbl.setText("Receiver Details");

        receivernamelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        receivernamelbl.setText("Receiver Name:");

        receiveraddresslbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        receiveraddresslbl.setText("Address:");

        receiverphonelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        receiverphonelbl.setText("Phone Number:");

        receiveremaillbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        receiveremaillbl.setText("Email Address:");

        addressReceiverlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        namereceiverlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(receivernamelbl)
                            .addComponent(receiverphonelbl)
                            .addComponent(receiveraddresslbl)
                            .addComponent(receiveremaillbl)))
                    .addComponent(deliverystatuslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliverystatuscbox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namereceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonereceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailreceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressReceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(deliveryreceiverlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(deliveryreceiverlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(receivernamelbl)
                    .addComponent(namereceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(receiveraddresslbl)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addressReceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(receiverphonelbl)
                    .addComponent(phonereceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiveremaillbl)
                    .addComponent(emailreceiverlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliverystatuscbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliverystatuslbl))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 450, 280));

        jPanel3.setBackground(new java.awt.Color(21, 71, 52));

        idcustlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        idcustlbl.setForeground(new java.awt.Color(240, 240, 240));
        idcustlbl.setText("Custid:");

        itemlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        itemlbl.setForeground(new java.awt.Color(240, 240, 240));
        itemlbl.setText("RM");

        Wcmlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Wcmlbl.setForeground(new java.awt.Color(240, 240, 240));
        Wcmlbl.setText("cm");

        Hcmlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Hcmlbl.setForeground(new java.awt.Color(240, 240, 240));
        Hcmlbl.setText("cm");

        Lcmlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Lcmlbl.setForeground(new java.awt.Color(240, 240, 240));
        Lcmlbl.setText("cm");

        detailsOrderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        detailsOrderlbl.setForeground(new java.awt.Color(240, 240, 240));

        idorderlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        idorderlbl.setForeground(new java.awt.Color(240, 240, 240));
        idorderlbl.setText("Orderid:");

        custidlbl.setForeground(new java.awt.Color(240, 240, 240));

        weightlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        weightlbl.setForeground(new java.awt.Color(240, 240, 240));
        weightlbl.setText("Weight:");

        itemlbl2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        itemlbl2.setForeground(new java.awt.Color(240, 240, 240));
        itemlbl2.setText("RM");

        total1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        total1lbl.setForeground(new java.awt.Color(240, 240, 240));

        itempricelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        itempricelbl.setForeground(new java.awt.Color(240, 240, 240));
        itempricelbl.setText("Item Price:");

        heightlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        heightlbl.setForeground(new java.awt.Color(240, 240, 240));
        heightlbl.setText("H:");

        width1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        width1lbl.setForeground(new java.awt.Color(240, 240, 240));

        deliveryOrderlbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        deliveryOrderlbl.setForeground(new java.awt.Color(240, 240, 240));
        deliveryOrderlbl.setText("Delivery");

        deliveryidlbl.setForeground(new java.awt.Color(240, 240, 240));

        itemlbl1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        itemlbl1.setForeground(new java.awt.Color(240, 240, 240));
        itemlbl1.setText("RM");

        assignedpersonlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        assignedpersonlbl.setForeground(new java.awt.Color(240, 240, 240));
        assignedpersonlbl.setText("Assigned Delivery Person: ");

        shippingfeelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        shippingfeelbl.setForeground(new java.awt.Color(240, 240, 240));
        shippingfeelbl.setText("Shipping Fee:");

        itemprice1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        itemprice1lbl.setForeground(new java.awt.Color(240, 240, 240));

        totallbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        totallbl.setForeground(new java.awt.Color(240, 240, 240));
        totallbl.setText("Total: ");

        height1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        height1lbl.setForeground(new java.awt.Color(240, 240, 240));

        orderdetailslbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        orderdetailslbl.setForeground(new java.awt.Color(240, 240, 240));
        orderdetailslbl.setText("Order Details: ");

        orderidlbl.setForeground(new java.awt.Color(240, 240, 240));

        deletebtn.setBackground(new java.awt.Color(129, 182, 157));
        deletebtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        lengthlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lengthlbl.setForeground(new java.awt.Color(240, 240, 240));
        lengthlbl.setText("L:");

        assignedperson1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        assignedperson1lbl.setForeground(new java.awt.Color(240, 240, 240));

        length1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        length1lbl.setForeground(new java.awt.Color(240, 240, 240));

        weight1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        weight1lbl.setForeground(new java.awt.Color(240, 240, 240));

        assignedpersonphonelbl1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        assignedpersonphonelbl1.setForeground(new java.awt.Color(240, 240, 240));
        assignedpersonphonelbl1.setText("Delivery Staff Contact No.: ");

        shippingfee1lbl2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        shippingfee1lbl2.setForeground(new java.awt.Color(240, 240, 240));

        phonestafflbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        phonestafflbl.setForeground(new java.awt.Color(240, 240, 240));

        Datelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Datelbl.setForeground(new java.awt.Color(240, 240, 240));
        Datelbl.setText("Date:");

        shippingfee1lbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        shippingfee1lbl.setForeground(new java.awt.Color(240, 240, 240));

        iddeliverylbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        iddeliverylbl.setForeground(new java.awt.Color(240, 240, 240));
        iddeliverylbl.setText("Deliveryid:");

        widthlbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        widthlbl.setForeground(new java.awt.Color(240, 240, 240));
        widthlbl.setText("W:");

        kglbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        kglbl.setForeground(new java.awt.Color(240, 240, 240));
        kglbl.setText("KG");

        datelbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        datelbl.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryOrderlbl)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(Datelbl)
                        .addGap(10, 10, 10)
                        .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(weightlbl)
                        .addGap(9, 9, 9)
                        .addComponent(weight1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(kglbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(widthlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(lengthlbl))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(length1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(width1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(shippingfee1lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(Wcmlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(Lcmlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(heightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(height1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Hcmlbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(shippingfeelbl))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(itempricelbl))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(totallbl))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(assignedpersonphonelbl1))
                            .addComponent(assignedpersonlbl))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(itemlbl2)
                                        .addGap(6, 6, 6)
                                        .addComponent(shippingfee1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(itemlbl)
                                        .addGap(6, 6, 6)
                                        .addComponent(itemprice1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(itemlbl1)
                                        .addGap(6, 6, 6)
                                        .addComponent(total1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(phonestafflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addComponent(orderdetailslbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detailsOrderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(assignedperson1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(451, 451, 451))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(idorderlbl)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(idcustlbl))
                            .addComponent(orderidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(custidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(iddeliverylbl)
                        .addGap(6, 6, 6)
                        .addComponent(deliveryidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletebtn)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(deliveryOrderlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idorderlbl)
                    .addComponent(idcustlbl)
                    .addComponent(orderidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddeliverylbl)
                    .addComponent(deliveryidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Datelbl)
                    .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightlbl)
                    .addComponent(weight1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kglbl))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(widthlbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lengthlbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(length1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(width1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shippingfee1lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Wcmlbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Lcmlbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(heightlbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(height1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Hcmlbl)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(shippingfeelbl)
                        .addGap(10, 10, 10)
                        .addComponent(itempricelbl)
                        .addGap(6, 6, 6)
                        .addComponent(totallbl)
                        .addGap(10, 10, 10)
                        .addComponent(assignedpersonphonelbl1)
                        .addGap(8, 8, 8)
                        .addComponent(assignedpersonlbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemlbl2)
                            .addComponent(shippingfee1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemlbl)
                            .addComponent(itemprice1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemlbl1)
                            .addComponent(total1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(phonestafflbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(assignedperson1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(orderdetailslbl)
                    .addComponent(detailsOrderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(deletebtn)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 890, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fillstatuscombo(){
        deliverystatuscbox.addItem("Pending");
        deliverystatuscbox.addItem("Processing");
        deliverystatuscbox.addItem("Shipping");
        deliverystatuscbox.addItem("Delivered");
    }
    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
           try {
                File file = new File("UserDetails.txt");
                Scanner sc = new Scanner(file);
                String temp;
                boolean found = false;
            
                while(sc.hasNext() && !found) {
                    temp = sc.nextLine();
                    String[] tempArr;
                    tempArr = temp.split(",");

                    if(Userid.equals(tempArr[0])) {
                        String TempUserType = tempArr[2]; // Return the usertype to the variable
                        Users u = new Users();
                        u.setSelectedUserType(TempUserType);
                        if (u.getSelectedUserType().equals("Customer")) {
                            new CustomerOrderTable(Userid).setVisible(true);
                            this.dispose();
                        } else if (u.getSelectedUserType().equals("Managing Staff")) {
                             new ManagingStaffAllOrder(Userid).setVisible(true);
                             this.dispose();
                        } else {
                             new DeliveryStaffOrderPage(Userid).setVisible(true);           
                             this.dispose();
                        }
                    }
                }
          } catch (Exception ex) {
            ex.toString();
          }     
    }//GEN-LAST:event_backbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String TempUserID = Userid;
        String ExistOrderID = orderidlbl.getText();
        String Tempcustid = custidlbl.getText();
        String deliveryid = deliveryidlbl.getText();
        String Tempsendname = namesenderlbl.getText();
        String Tempsendaddress = addressSenderlbl.getText();
        String Tempsendphone = phonesenderlbl.getText();
        String Tempsendemail = emailsenderlbl.getText();
        String Tempreceivename = namereceiverlbl.getText();
        String Tempreceiveaddress = addressReceiverlbl.getText();
        String Tempreceivephone= phonereceiverlbl.getText();
        String Tempreceiveemail = emailreceiverlbl.getText();
        String Tempdate = datelbl.getText();
        String Tempweight= weight1lbl.getText();
        String Tempwidth = width1lbl.getText();
        String Templength = length1lbl.getText();
        String Tempheight = height1lbl.getText();
        String Temporderdetails = detailsOrderlbl.getText();
        String Tempshippingfee= shippingfee1lbl.getText();
        String Tempitemprice = itemprice1lbl.getText();
        String Temptotal =total1lbl.getText();
        String Tempstaffphone = phonestafflbl.getText();
        String Tempdeliverystatus = deliverystatuscbox.getSelectedItem().toString();

        try{
            File file = new File("UserDetails.txt");
            Scanner sc = new Scanner(file);
            //read data from the file
            String temp;
            boolean found = false;

            while(sc.hasNext() && !found /*the system will stop running while it found the correct username and password*/) {
                temp = sc.nextLine(); //read a line of text from file
                String[] tempArr;
                tempArr = temp.split (",");
                if (TempUserID.equals(tempArr[0])) {
                    String Temptype = tempArr[2];
                    Users u = new Users();
                    u.setSelectedUserType(Temptype);

                    Orders o = new Orders(ExistOrderID, Tempsendname,Tempsendaddress,Tempsendphone,Tempsendemail,Tempreceivename,Tempreceiveaddress,Tempreceivephone,Tempreceiveemail,Tempdate,Tempweight,Tempwidth,
                        Templength,Tempheight,Temporderdetails,Tempshippingfee,Tempitemprice,Temptotal,Tempdeliverystatus,deliveryid, Tempstaffphone,Tempcustid);

                    if(u.getSelectedUserType().equals("Customer")) {
                        if(Tempdeliverystatus.equals("Pending")) {
                            o.RemoveOrder();
                            o.DeletedOrder();
                            this.dispose();
                            new CustomerOrderTable(Userid).setVisible(true);
                        }else{
                             JOptionPane.showMessageDialog(rootPane, "You are not allowed to delete the order since the orders are not in the pending stage. ", "Delivery Status", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }else if(u.getSelectedUserType().equals("Delivery Staff")){
                        o.RemoveOrder();
                        o.UpdateOrder();
                        this.dispose();
                        new DeliveryStaffOrderPage(Userid).setVisible(true);
                    }                            
                }
            }
        } catch(FileNotFoundException ex) {
            ex.toString();
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void deliverystatuscboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverystatuscboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliverystatuscboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ViewOrderDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Datelbl;
    private javax.swing.JLabel Hcmlbl;
    private javax.swing.JLabel Lcmlbl;
    private javax.swing.JLabel Wcmlbl;
    private javax.swing.JLabel addressReceiverlbl;
    private javax.swing.JLabel addressSenderlbl;
    private javax.swing.JLabel assignedperson1lbl;
    private javax.swing.JLabel assignedpersonlbl;
    private javax.swing.JLabel assignedpersonphonelbl1;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel custidlbl;
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel deliveryOrderlbl;
    private javax.swing.JLabel deliveryidlbl;
    private javax.swing.JLabel deliveryreceiverlbl;
    private javax.swing.JLabel deliverysenderlbl;
    private javax.swing.JComboBox<String> deliverystatuscbox;
    private javax.swing.JLabel deliverystatuslbl;
    private javax.swing.JLabel detailsOrderlbl;
    private javax.swing.JLabel emailreceiverlbl;
    private javax.swing.JLabel emailsenderlbl;
    private javax.swing.JLabel height1lbl;
    private javax.swing.JLabel heightlbl;
    private javax.swing.JLabel idcustlbl;
    private javax.swing.JLabel iddeliverylbl;
    private javax.swing.JLabel idorderlbl;
    private javax.swing.JLabel itemlbl;
    private javax.swing.JLabel itemlbl1;
    private javax.swing.JLabel itemlbl2;
    private javax.swing.JLabel itemprice1lbl;
    private javax.swing.JLabel itempricelbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel kglbl;
    private javax.swing.JLabel length1lbl;
    private javax.swing.JLabel lengthlbl;
    private javax.swing.JLabel namereceiverlbl;
    private javax.swing.JLabel namesenderlbl;
    private javax.swing.JLabel orderdetailslbl;
    private javax.swing.JLabel orderidlbl;
    private javax.swing.JLabel phonereceiverlbl;
    private javax.swing.JLabel phonesenderlbl;
    private javax.swing.JLabel phonestafflbl;
    private javax.swing.JLabel receiveraddresslbl;
    private javax.swing.JLabel receiveremaillbl;
    private javax.swing.JLabel receivernamelbl;
    private javax.swing.JLabel receiverphonelbl;
    private javax.swing.JLabel senderaddresslbl;
    private javax.swing.JLabel senderemaillbl;
    private javax.swing.JLabel sendernamelbl;
    private javax.swing.JLabel senderphonelbl;
    private javax.swing.JLabel shippingfee1lbl;
    private javax.swing.JLabel shippingfee1lbl2;
    private javax.swing.JLabel shippingfeelbl;
    private javax.swing.JLabel total1lbl;
    private javax.swing.JLabel totallbl;
    private javax.swing.JLabel weight1lbl;
    private javax.swing.JLabel weightlbl;
    private javax.swing.JLabel width1lbl;
    private javax.swing.JLabel widthlbl;
    // End of variables declaration//GEN-END:variables
}
